name: Link Check
on:
  push:
    branches: ["main"]
    paths: ["site/current/**", ".github/workflows/linkcheck.yml"]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --base ./site/current ./site/current
