name: Build players.csv

on:
  push:
    branches: [ main ]   # change if your default branch differs
  schedule:
    - cron: '0 9 * * *'  # daily 02:00 PT (09:00 UTC)

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_players.py

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update players.csv from A–Z scrape"
          file_pattern: players.csv players.xlsx
