name: Sync site/current to docs

on:
  push:
    branches: [ "main" ]
    paths:
      - 'site/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure .nojekyll at repo root
        run: |
          touch .nojekyll

      - name: Sync site/current to docs
        run: |
          rm -rf docs
          mkdir -p docs
          cp -R site/current/* docs/ || true

      - name: Commit and push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Sync site/current to docs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
